-- BIS SIH26107 - PHASE 3 loader. Run with psql from POSTGRES_READY/:
--   psql -v ON_ERROR_STOP=1 -f DDL.sql -f LOAD.sql
SET search_path TO bis, public;

\copy is_master (is_id, canonical_is_number, display_is_number, raw_is_number_variants, standard_number, standard_year, part_number, section_number, amendment_reference, iec_reference, part_source, is_iec_flag, title, title_vernacular, standard_scope, part_section_label, revision, version, publication_date, publication_date_precision, revision_date, reaffirmation_review_date, standard_status, standard_status_original, superseded_standard, superseding_standard, technical_committee, subcommittee, product_category, degree_of_equivalence, mandatory_voluntary, certification_type, official_url, document_url, source_url, source_reference_label, parse_status, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/IS_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_master (product_id, product_name, alternate_names, product_category, product_subcategory, product_description, keywords, product_group, certification_scheme_to_store, source_product_ids, source_url, source_reference_label, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/PRODUCT_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy qco_master (qco_id, qco_name, qco_number, qco_number_normalized, qco_product_text, notification_number, notification_date, notification_date_precision, effective_date, effective_date_precision, ministry, department, mandatory_status, mandatory_status_original, qco_scope, qco_exclusions, qco_exemptions, qco_amendments, qco_extensions, qco_deferments, qco_corrigendas, qco_supersession, qco_status, qco_status_original, qco_scope_exclusions_amendments_combined, qco_schemes_text, official_document_url, source_gazette_url, source_url, source_reference_label, source_qco_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/QCO_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy scheme_master (scheme_id, scheme_name, scheme_code, scheme_label, scheme_type, certification_type, mandatory_voluntary, mandatory_voluntary_original, certification_scope, certification_requirements, fmcs_requirements, guideline_title, applicability, application_procedure, fee_structure, inspection_testing_norm, document_url, source_url, source_reference_label, source_scheme_ids, source_scheme_record_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/SCHEME_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_manual_master (pm_id, manual_title, manual_version, revision_date, revision_date_precision, document_scope, pm_scheme_text, is_id, canonical_is_number, product_id, product_name, document_id, document_url, source_url, source_reference_label, source_manual_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/PRODUCT_MANUAL_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy test_master (test_id, test_name, test_parameter, test_method, test_method_standard, method_standard_is_id, clause, sample_size, sampling_frequency, test_frequency, acceptance_criteria, required_equipment, laboratory_requirement, rejection_handling, remarks, source_document, source_page, source_url, source_reference_label, source_test_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/TEST_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy lab_master (lab_id, lab_name, lab_code, lab_type, address, city, district, state, pin, contact_person, contact_number, email, contact_details, recognition_status, recognition_status_original, validity, validity_date, accreditation_validity, scope_url, source_url, source_reference_label, source_lab_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/LAB_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy document_master (document_id, document_type, title, is_id, canonical_is_number, product_id, scheme_id, qco_id, version, publication_date, effective_date, source_url, download_url, local_path, sha256, access_type, parser_status, retrieved_at, page_count, http_status, content_type, bytes, last_modified, dedup_status, license_access_restriction, source_reference_label, source_document_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/DOCUMENT_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy faq_master (faq_id, question, answer, faq_category, related_is_text, related_product_text, related_qco_text, related_scheme_text, document_reference, source_url, source_reference_label, source_faq_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/FAQ_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy notification_master (notification_id, notification_type, notification_number, notification_number_normalized, title, title_vernacular, notification_category, notification_date, effective_date, ministry, department, subject, related_is_text, related_qco_text, related_amendment_text, document_url, source_url, source_reference_label, source_notification_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/NOTIFICATION_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy legal_master (legal_id, legal_instrument_type, instrument_number, instrument_number_normalized, title, issuing_authority, ministry, release_date, effective_date, subject, metal, fineness, mandatory_status, mandatory_status_original, geographical_applicability, district_phase, amendment, exemption, supersession, implementation_instructions, related_is_text, document_url, source_url, source_reference_label, source_legal_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/LEGAL_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy hallmarking_master (hm_id, centre_name, centre_code, hallmarking_entity_type, address, city, district, state, pin, recognition_status, recognition_status_original, recognition_status_raw, validity, validity_date, suspended_cancelled_date, region, centre_type, hallmarking_scope, services, source_url, source_reference_label, source_centre_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/HALLMARKING_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy fmcs_master (fmcs_id, manufacturer_name, country, factory, cml_licence_no, licence, licence_status, licence_status_original, validity_date, is_id, canonical_is_number, fmcs_product, variety_brand, name_address_raw, fmcs_eligibility, machinery_requirements, testing_facilities, competent_personnel, air_requirements, application_requirements, fees, fmcs_documents, source_url, source_reference_label, source_fmcs_ids, source_file_count, source_file_ids, source_files, source_sheets, source_rows, record_disposition, conflict_count, conflict_fields, review_flag, review_reason, populated_field_count, completeness_pct) FROM '../00_MASTER/FMCS_MASTER.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_product_mapping (relationship_id, is_id, canonical_is_number, product_id, product_name, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_PRODUCT_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_qco_mapping (relationship_id, is_id, canonical_is_number, qco_id, qco_number, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_QCO_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_scheme_mapping (relationship_id, is_id, canonical_is_number, scheme_id, scheme_name, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_SCHEME_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_document_mapping (relationship_id, is_id, canonical_is_number, document_id, document_type, title, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_DOCUMENT_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_test_mapping (relationship_id, is_id, canonical_is_number, test_id, test_name, clause_reference, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_TEST_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_lab_test_mapping (relationship_id, is_id, canonical_is_number, lab_id, lab_name, test_id, test_name, capability, scope_status, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_LAB_TEST_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_related_is (relationship_id, is_id, canonical_is_number, related_is_id, related_canonical_is_number, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_RELATED_IS.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy qco_scheme_mapping (relationship_id, qco_id, qco_number, scheme_id, scheme_name, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/QCO_SCHEME_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_document_mapping (relationship_id, product_id, product_name, document_id, document_type, title, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/PRODUCT_DOCUMENT_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy test_lab_mapping (relationship_id, test_id, test_name, lab_id, lab_name, capability, testing_charge, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/TEST_LAB_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy notification_entity_mapping (relationship_id, notification_id, notification_number, target_entity, target_entity_id, target_entity_label, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/NOTIFICATION_ENTITY_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_amendments (relationship_id, is_id, canonical_is_number, amendment_reference, amendment_date, amended_from_version, amended_to_version, amendment_status, superseded_standard, superseding_standard, document_id, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_AMENDMENTS.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_product_manual_mapping (relationship_id, is_id, canonical_is_number, manual_id, manual_title, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_PRODUCT_MANUAL_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_fmcs_mapping (relationship_id, is_id, canonical_is_number, fmcs_id, cml_licence_no, manufacturer_name, country, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_FMCS_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy entity_document_mapping (relationship_id, entity_type, entity_id, entity_label, document_id, document_type, title, source_url, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/ENTITY_DOCUMENT_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy scheme_product_mapping (relationship_id, scheme_id, scheme_name, product_id, product_name, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/SCHEME_PRODUCT_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy hallmarking_centre_scope (relationship_id, centre_id, centre_name, scope_item, recognition_status, city, state, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/HALLMARKING_CENTRE_SCOPE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy is_entity_mapping (relationship_id, is_id, canonical_is_number, entity_type, entity_id, entity_label, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/IS_ENTITY_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy qco_product_mapping (relationship_id, qco_id, qco_number, product_id, product_name, relationship_type, relation_context, evidence_column, evidence_value, unmatched_reference, source_file_ids, source_files, source_sheets, source_rows, confidence, review_flag) FROM '../90_RELATIONSHIPS/QCO_PRODUCT_MAPPING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_manual_infrastructure (pm_section_id, pm_id, manual_title, manual_version, is_id, canonical_is_number, product_id, product_name, section_category, source_column, requirement_text, text_length, clause, source_file_id, source_file, source_sheet, source_row, source_url, review_flag) FROM '../00_MASTER/PRODUCT_MANUAL_INFRASTRUCTURE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_manual_marking (pm_section_id, pm_id, manual_title, manual_version, is_id, canonical_is_number, product_id, product_name, section_category, source_column, requirement_text, text_length, clause, source_file_id, source_file, source_sheet, source_row, source_url, review_flag) FROM '../00_MASTER/PRODUCT_MANUAL_MARKING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_manual_requirements (pm_section_id, pm_id, manual_title, manual_version, is_id, canonical_is_number, product_id, product_name, section_category, source_column, requirement_text, text_length, clause, source_file_id, source_file, source_sheet, source_row, source_url, review_flag) FROM '../00_MASTER/PRODUCT_MANUAL_REQUIREMENTS.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_manual_sampling (pm_section_id, pm_id, manual_title, manual_version, is_id, canonical_is_number, product_id, product_name, section_category, source_column, requirement_text, text_length, clause, source_file_id, source_file, source_sheet, source_row, source_url, review_flag) FROM '../00_MASTER/PRODUCT_MANUAL_SAMPLING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy product_manual_testing (pm_section_id, pm_id, manual_title, manual_version, is_id, canonical_is_number, product_id, product_name, section_category, source_column, requirement_text, text_length, clause, source_file_id, source_file, source_sheet, source_row, source_url, review_flag) FROM '../00_MASTER/PRODUCT_MANUAL_TESTING.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy entity_attributes (attribute_id, entity_type, entity_id, entity_label, attribute_name, attribute_value, value_length, semantic_type, attribute_context, null_class, original_value, missing_reason, source_file_id, source_file, source_sheet, source_row, source_column, transformation_rule, merge_action, rule_source, source_url, review_flag) FROM '../00_MASTER/ENTITY_ATTRIBUTES.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy record_provenance (provenance_id, provenance_origin, entity_type, entity_id, entity_label, canonical_column, canonical_value, source_file_id, source_file, source_sheet, source_row, source_column, source_value, null_class, missing_reason, transformation_rule, merge_action, rule_source, record_disposition, source_url, source_title, source_type, document_id, document_title, page, section, clause, version, effective_date, document_hash, retrieved_at, evidence_text, verification_status, confidence) FROM '../91_PROVENANCE/RECORD_PROVENANCE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy source_file_provenance (source_file_id, original_filename, extension, exact_path, source_location, sha256, file_size_bytes, encoding, sheet_name, sheet_count, total_data_rows, total_columns, canonical_target, canonical_dataset, candidate_topic, rows_read, cells_projected, records_canonical, records_merged, records_conflict_preserved, records_requires_review, records_not_applicable, records_accounted, retention_decision, archive_path, structural_issue, analysis_status, modified_time_utc, notes) FROM '../91_PROVENANCE/SOURCE_FILE_PROVENANCE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy document_provenance (document_provenance_id, document_id, document_type, title, is_id, canonical_is_number, source_url, download_url, local_path, sha256, page_count, http_status, content_type, bytes, last_modified, access_type, parser_status, dedup_status, retrieved_at, chunk_count, evidence_row_count, source_file_id, source_file, source_sheet, source_row, notes) FROM '../91_PROVENANCE/DOCUMENT_PROVENANCE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy conflict_status (conflict_id, entity_type, entity_id, entity_label, field, source_a, source_a_file_id, value_a, source_row_a, date_a, source_b, source_b_file_id, value_b, source_row_b, date_b, resolution_status, resolution_rule, resolution_reason, canonical_value, confidence, review_flag) FROM '../92_VALIDATION/CONFLICT_STATUS.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy requires_review (review_id, entity_type, entity_id, entity_label, field, field_value, review_class, review_reason, required_action, source_file_id, source_file, source_sheet, source_row, attempted_source_url, phase2_verdict, resolution_status) FROM '../92_VALIDATION/REQUIRES_REVIEW.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy data_loss_audit (source_file_id, source_file, source_sheet, source_row, route_target, entity_type, entity_id, entity_label, record_disposition, disposition_reason, fields_projected, fields_populated, attributes_written, relationships_written, provenance_rows) FROM '../92_VALIDATION/DATA_LOSS_AUDIT.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy orphan_records (relationship_table, relationship_type, unmatched_reference, evidence_column, evidence_value, resolved_sides, source_file_id, source_file, source_sheet, source_row, reason) FROM '../92_VALIDATION/ORPHAN_RECORDS.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy extraction_log (url, error_type, event_timestamp, retry_count, outcome, notes, source_file_id, source_file, source_sheet, source_row, record_disposition) FROM '../93_OPERATIONAL/EXTRACTION_LOG.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy fmcs_country_coverage (country, manufacturer_count, licence_count, source_file_id, source_file, source_sheet, source_row, record_disposition) FROM '../00_MASTER/FMCS_COUNTRY_COVERAGE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy fmcs_is_coverage (is_id, canonical_is_number, manufacturer_count, licence_count, source_file_id, source_file, source_sheet, source_row, record_disposition) FROM '../00_MASTER/FMCS_IS_COVERAGE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');
\copy lab_scope (lab_id, test_id, is_id, source_scope_ids, source_lab_ids, canonical_is_number, product_name, test_name, test_method_standard, clause_reference, capability, scope_status, scope_validity, testing_charge, source_url, source_file_id, source_file, source_sheet, source_row, record_disposition) FROM '../00_MASTER/LAB_SCOPE.csv' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8');

-- Referential integrity is asserted only after the data is loaded,
-- so a failure here means a real orphan, not a load-order problem.
-- 92_VALIDATION/ORPHAN_RECORDS.csv lists every reference that could not
-- be resolved; those columns are NULL and therefore FK-legal.

ALTER TABLE is_product_mapping ADD CONSTRAINT fk_is_product_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_product_mapping ADD CONSTRAINT fk_is_product_mapping_product_id FOREIGN KEY (product_id) REFERENCES product_master (product_id);
ALTER TABLE is_qco_mapping ADD CONSTRAINT fk_is_qco_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_qco_mapping ADD CONSTRAINT fk_is_qco_mapping_qco_id FOREIGN KEY (qco_id) REFERENCES qco_master (qco_id);
ALTER TABLE is_scheme_mapping ADD CONSTRAINT fk_is_scheme_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_scheme_mapping ADD CONSTRAINT fk_is_scheme_mapping_scheme_id FOREIGN KEY (scheme_id) REFERENCES scheme_master (scheme_id);
ALTER TABLE is_document_mapping ADD CONSTRAINT fk_is_document_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_document_mapping ADD CONSTRAINT fk_is_document_mapping_document_id FOREIGN KEY (document_id) REFERENCES document_master (document_id);
ALTER TABLE is_test_mapping ADD CONSTRAINT fk_is_test_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_test_mapping ADD CONSTRAINT fk_is_test_mapping_test_id FOREIGN KEY (test_id) REFERENCES test_master (test_id);
ALTER TABLE is_lab_test_mapping ADD CONSTRAINT fk_is_lab_test_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_lab_test_mapping ADD CONSTRAINT fk_is_lab_test_mapping_lab_id FOREIGN KEY (lab_id) REFERENCES lab_master (lab_id);
ALTER TABLE is_lab_test_mapping ADD CONSTRAINT fk_is_lab_test_mapping_test_id FOREIGN KEY (test_id) REFERENCES test_master (test_id);
ALTER TABLE is_related_is ADD CONSTRAINT fk_is_related_is_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_related_is ADD CONSTRAINT fk_is_related_is_related_is_id FOREIGN KEY (related_is_id) REFERENCES is_master (is_id);
ALTER TABLE qco_scheme_mapping ADD CONSTRAINT fk_qco_scheme_mapping_qco_id FOREIGN KEY (qco_id) REFERENCES qco_master (qco_id);
ALTER TABLE qco_scheme_mapping ADD CONSTRAINT fk_qco_scheme_mapping_scheme_id FOREIGN KEY (scheme_id) REFERENCES scheme_master (scheme_id);
ALTER TABLE product_document_mapping ADD CONSTRAINT fk_product_document_mapping_product_id FOREIGN KEY (product_id) REFERENCES product_master (product_id);
ALTER TABLE product_document_mapping ADD CONSTRAINT fk_product_document_mapping_document_id FOREIGN KEY (document_id) REFERENCES document_master (document_id);
ALTER TABLE test_lab_mapping ADD CONSTRAINT fk_test_lab_mapping_test_id FOREIGN KEY (test_id) REFERENCES test_master (test_id);
ALTER TABLE test_lab_mapping ADD CONSTRAINT fk_test_lab_mapping_lab_id FOREIGN KEY (lab_id) REFERENCES lab_master (lab_id);
ALTER TABLE notification_entity_mapping ADD CONSTRAINT fk_notification_entity_mapping_notification_id FOREIGN KEY (notification_id) REFERENCES notification_master (notification_id);
ALTER TABLE is_amendments ADD CONSTRAINT fk_is_amendments_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_amendments ADD CONSTRAINT fk_is_amendments_document_id FOREIGN KEY (document_id) REFERENCES document_master (document_id);
ALTER TABLE is_product_manual_mapping ADD CONSTRAINT fk_is_product_manual_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_product_manual_mapping ADD CONSTRAINT fk_is_product_manual_mapping_manual_id FOREIGN KEY (manual_id) REFERENCES product_manual_master (pm_id);
ALTER TABLE is_fmcs_mapping ADD CONSTRAINT fk_is_fmcs_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE is_fmcs_mapping ADD CONSTRAINT fk_is_fmcs_mapping_fmcs_id FOREIGN KEY (fmcs_id) REFERENCES fmcs_master (fmcs_id);
ALTER TABLE entity_document_mapping ADD CONSTRAINT fk_entity_document_mapping_document_id FOREIGN KEY (document_id) REFERENCES document_master (document_id);
ALTER TABLE scheme_product_mapping ADD CONSTRAINT fk_scheme_product_mapping_scheme_id FOREIGN KEY (scheme_id) REFERENCES scheme_master (scheme_id);
ALTER TABLE scheme_product_mapping ADD CONSTRAINT fk_scheme_product_mapping_product_id FOREIGN KEY (product_id) REFERENCES product_master (product_id);
ALTER TABLE hallmarking_centre_scope ADD CONSTRAINT fk_hallmarking_centre_scope_centre_id FOREIGN KEY (centre_id) REFERENCES hallmarking_master (hm_id);
ALTER TABLE is_entity_mapping ADD CONSTRAINT fk_is_entity_mapping_is_id FOREIGN KEY (is_id) REFERENCES is_master (is_id);
ALTER TABLE qco_product_mapping ADD CONSTRAINT fk_qco_product_mapping_qco_id FOREIGN KEY (qco_id) REFERENCES qco_master (qco_id);
ALTER TABLE qco_product_mapping ADD CONSTRAINT fk_qco_product_mapping_product_id FOREIGN KEY (product_id) REFERENCES product_master (product_id);
ALTER TABLE product_manual_infrastructure ADD CONSTRAINT fk_product_manual_infrastructure_pm_id FOREIGN KEY (pm_id) REFERENCES product_manual_master (pm_id);
ALTER TABLE product_manual_marking ADD CONSTRAINT fk_product_manual_marking_pm_id FOREIGN KEY (pm_id) REFERENCES product_manual_master (pm_id);
ALTER TABLE product_manual_requirements ADD CONSTRAINT fk_product_manual_requirements_pm_id FOREIGN KEY (pm_id) REFERENCES product_manual_master (pm_id);
ALTER TABLE product_manual_sampling ADD CONSTRAINT fk_product_manual_sampling_pm_id FOREIGN KEY (pm_id) REFERENCES product_manual_master (pm_id);
ALTER TABLE product_manual_testing ADD CONSTRAINT fk_product_manual_testing_pm_id FOREIGN KEY (pm_id) REFERENCES product_manual_master (pm_id);
CREATE INDEX ix_attr_entity ON entity_attributes (entity_type, entity_id);
CREATE INDEX ix_prov_entity ON record_provenance (entity_type, entity_id);
CREATE INDEX ix_prov_file ON record_provenance (source_file_id);
CREATE INDEX ix_conf_entity ON conflict_status (entity_type, entity_id);
CREATE INDEX ix_dla_file ON data_loss_audit (source_file_id);
CREATE INDEX ix_std_num ON is_master (canonical_is_number);

\copy unresolved_relationship_references FROM '93_OPERATIONAL/UNRESOLVED_RELATIONSHIP_REFERENCES.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
