-- BIS SIH26107 PHASE 4 - Supabase PostgreSQL schema.
-- Section 1 is POSTGRES_READY/DDL.sql from the FROZEN Phase 3, inlined byte for
-- byte. Phase 4 does not redesign the data model.
--   source : BIS_SIH26107_DATA/POSTGRES_READY/DDL.sql
--   sha256 : 23df8be0da588a6b709e8d5d94afc96f178c132194b2e7ef8adb52870246c675
-- Section 2 adds read-only views only, so the Phase-4 spec's plain table names
-- resolve without duplicating a single row.
-- Objects live in schema "bis", not "public": Supabase does not expose bis
-- through its auto-generated REST API, so loading data creates no public surface.

-- ===================== SECTION 1: FROZEN PHASE-3 DDL =====================
-- BIS SIH26107 - PHASE 3 canonical layer, PostgreSQL DDL
-- Generated by p3_build.py. Every table maps 1:1 to a canonical CSV that
-- stays in place under BIS_SIH26107_DATA/; nothing is duplicated here, so
-- there is exactly one source of truth per table.
-- Empty CSV fields load as NULL. A NULL means 'not established by the
-- uploaded data' - the reason is in record_provenance.missing_reason.
CREATE SCHEMA IF NOT EXISTS bis;
SET search_path TO bis, public;

DROP TABLE IF EXISTS is_master CASCADE;
CREATE TABLE is_master (
    is_id                              text PRIMARY KEY,
    canonical_is_number                text,
    display_is_number                  text,
    raw_is_number_variants             text,
    standard_number                    text,
    standard_year                      integer,
    part_number                        text,
    section_number                     text,
    amendment_reference                text,
    iec_reference                      text,
    part_source                        text,
    is_iec_flag                        text,
    title                              text,
    title_vernacular                   text,
    standard_scope                     text,
    part_section_label                 text,
    revision                           text,
    version                            text,
    publication_date                   text,
    publication_date_precision         text,
    revision_date                      text,
    reaffirmation_review_date          text,
    standard_status                    text,
    standard_status_original           text,
    superseded_standard                text,
    superseding_standard               text,
    technical_committee                text,
    subcommittee                       text,
    product_category                   text,
    degree_of_equivalence              text,
    mandatory_voluntary                text,
    certification_type                 text,
    official_url                       text,
    document_url                       text,
    source_url                         text,
    source_reference_label             text,
    parse_status                       text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS product_master CASCADE;
CREATE TABLE product_master (
    product_id                         text PRIMARY KEY,
    product_name                       text,
    alternate_names                    text,
    product_category                   text,
    product_subcategory                text,
    product_description                text,
    keywords                           text,
    product_group                      text,
    certification_scheme_to_store      text,
    source_product_ids                 text,
    source_url                         text,
    source_reference_label             text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS qco_master CASCADE;
CREATE TABLE qco_master (
    qco_id                             text PRIMARY KEY,
    qco_name                           text,
    qco_number                         text,
    qco_number_normalized              text,
    qco_product_text                   text,
    notification_number                text,
    notification_date                  text,
    notification_date_precision        text,
    effective_date                     text,
    effective_date_precision           text,
    ministry                           text,
    department                         text,
    mandatory_status                   text,
    mandatory_status_original          text,
    qco_scope                          text,
    qco_exclusions                     text,
    qco_exemptions                     text,
    qco_amendments                     text,
    qco_extensions                     text,
    qco_deferments                     text,
    qco_corrigendas                    text,
    qco_supersession                   text,
    qco_status                         text,
    qco_status_original                text,
    qco_scope_exclusions_amendments_combined text,
    qco_schemes_text                   text,
    official_document_url              text,
    source_gazette_url                 text,
    source_url                         text,
    source_reference_label             text,
    source_qco_ids                     text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS scheme_master CASCADE;
CREATE TABLE scheme_master (
    scheme_id                          text PRIMARY KEY,
    scheme_name                        text,
    scheme_code                        text,
    scheme_label                       text,
    scheme_type                        text,
    certification_type                 text,
    mandatory_voluntary                text,
    mandatory_voluntary_original       text,
    certification_scope                text,
    certification_requirements         text,
    fmcs_requirements                  text,
    guideline_title                    text,
    applicability                      text,
    application_procedure              text,
    fee_structure                      text,
    inspection_testing_norm            text,
    document_url                       text,
    source_url                         text,
    source_reference_label             text,
    source_scheme_ids                  text,
    source_scheme_record_ids           text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS product_manual_master CASCADE;
CREATE TABLE product_manual_master (
    pm_id                              text PRIMARY KEY,
    manual_title                       text,
    manual_version                     text,
    revision_date                      text,
    revision_date_precision            text,
    document_scope                     text,
    pm_scheme_text                     text,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    product_name                       text,
    document_id                        text,
    document_url                       text,
    source_url                         text,
    source_reference_label             text,
    source_manual_ids                  text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS test_master CASCADE;
CREATE TABLE test_master (
    test_id                            text PRIMARY KEY,
    test_name                          text,
    test_parameter                     text,
    test_method                        text,
    test_method_standard               text,
    method_standard_is_id              text,
    clause                             text,
    sample_size                        text,
    sampling_frequency                 text,
    test_frequency                     text,
    acceptance_criteria                text,
    required_equipment                 text,
    laboratory_requirement             text,
    rejection_handling                 text,
    remarks                            text,
    source_document                    text,
    source_page                        text,
    source_url                         text,
    source_reference_label             text,
    source_test_ids                    text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS lab_master CASCADE;
CREATE TABLE lab_master (
    lab_id                             text PRIMARY KEY,
    lab_name                           text,
    lab_code                           text,
    lab_type                           text,
    address                            text,
    city                               text,
    district                           text,
    state                              text,
    pin                                text,
    contact_person                     text,
    contact_number                     text,
    email                              text,
    contact_details                    text,
    recognition_status                 text,
    recognition_status_original        text,
    validity                           text,
    validity_date                      text,
    accreditation_validity             text,
    scope_url                          text,
    source_url                         text,
    source_reference_label             text,
    source_lab_ids                     text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS document_master CASCADE;
CREATE TABLE document_master (
    document_id                        text PRIMARY KEY,
    document_type                      text,
    title                              text,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    scheme_id                          text,
    qco_id                             text,
    version                            text,
    publication_date                   text,
    effective_date                     text,
    source_url                         text,
    download_url                       text,
    local_path                         text,
    sha256                             text,
    access_type                        text,
    parser_status                      text,
    retrieved_at                       text,
    page_count                         integer,
    http_status                        text,
    content_type                       text,
    bytes                              integer,
    last_modified                      text,
    dedup_status                       text,
    license_access_restriction         text,
    source_reference_label             text,
    source_document_ids                text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS faq_master CASCADE;
CREATE TABLE faq_master (
    faq_id                             text PRIMARY KEY,
    question                           text,
    answer                             text,
    faq_category                       text,
    related_is_text                    text,
    related_product_text               text,
    related_qco_text                   text,
    related_scheme_text                text,
    document_reference                 text,
    source_url                         text,
    source_reference_label             text,
    source_faq_ids                     text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS notification_master CASCADE;
CREATE TABLE notification_master (
    notification_id                    text PRIMARY KEY,
    notification_type                  text,
    notification_number                text,
    notification_number_normalized     text,
    title                              text,
    title_vernacular                   text,
    notification_category              text,
    notification_date                  text,
    effective_date                     text,
    ministry                           text,
    department                         text,
    subject                            text,
    related_is_text                    text,
    related_qco_text                   text,
    related_amendment_text             text,
    document_url                       text,
    source_url                         text,
    source_reference_label             text,
    source_notification_ids            text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS legal_master CASCADE;
CREATE TABLE legal_master (
    legal_id                           text PRIMARY KEY,
    legal_instrument_type              text,
    instrument_number                  text,
    instrument_number_normalized       text,
    title                              text,
    issuing_authority                  text,
    ministry                           text,
    release_date                       text,
    effective_date                     text,
    subject                            text,
    metal                              text,
    fineness                           text,
    mandatory_status                   text,
    mandatory_status_original          text,
    geographical_applicability         text,
    district_phase                     text,
    amendment                          text,
    exemption                          text,
    supersession                       text,
    implementation_instructions        text,
    related_is_text                    text,
    document_url                       text,
    source_url                         text,
    source_reference_label             text,
    source_legal_ids                   text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS hallmarking_master CASCADE;
CREATE TABLE hallmarking_master (
    hm_id                              text PRIMARY KEY,
    centre_name                        text,
    centre_code                        text,
    hallmarking_entity_type            text,
    address                            text,
    city                               text,
    district                           text,
    state                              text,
    pin                                text,
    recognition_status                 text,
    recognition_status_original        text,
    recognition_status_raw             text,
    validity                           text,
    validity_date                      text,
    suspended_cancelled_date           text,
    region                             text,
    centre_type                        text,
    hallmarking_scope                  text,
    services                           text,
    source_url                         text,
    source_reference_label             text,
    source_centre_ids                  text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS fmcs_master CASCADE;
CREATE TABLE fmcs_master (
    fmcs_id                            text PRIMARY KEY,
    manufacturer_name                  text,
    country                            text,
    factory                            text,
    cml_licence_no                     text,
    licence                            text,
    licence_status                     text,
    licence_status_original            text,
    validity_date                      text,
    is_id                              text,
    canonical_is_number                text,
    fmcs_product                       text,
    variety_brand                      text,
    name_address_raw                   text,
    fmcs_eligibility                   text,
    machinery_requirements             text,
    testing_facilities                 text,
    competent_personnel                text,
    air_requirements                   text,
    application_requirements           text,
    fees                               text,
    fmcs_documents                     text,
    source_url                         text,
    source_reference_label             text,
    source_fmcs_ids                    text,
    source_file_count                  integer,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    record_disposition                 text,
    conflict_count                     integer,
    conflict_fields                    text,
    review_flag                        text,
    review_reason                      text,
    populated_field_count              integer,
    completeness_pct                   numeric
);

DROP TABLE IF EXISTS is_product_mapping CASCADE;
CREATE TABLE is_product_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    product_name                       text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_qco_mapping CASCADE;
CREATE TABLE is_qco_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    qco_id                             text,
    qco_number                         text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_scheme_mapping CASCADE;
CREATE TABLE is_scheme_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    scheme_id                          text,
    scheme_name                        text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_document_mapping CASCADE;
CREATE TABLE is_document_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    document_id                        text,
    document_type                      text,
    title                              text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_test_mapping CASCADE;
CREATE TABLE is_test_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    test_id                            text,
    test_name                          text,
    clause_reference                   text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_lab_test_mapping CASCADE;
CREATE TABLE is_lab_test_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    lab_id                             text,
    lab_name                           text,
    test_id                            text,
    test_name                          text,
    capability                         text,
    scope_status                       text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_related_is CASCADE;
CREATE TABLE is_related_is (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    related_is_id                      text,
    related_canonical_is_number        text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS qco_scheme_mapping CASCADE;
CREATE TABLE qco_scheme_mapping (
    relationship_id                    text PRIMARY KEY,
    qco_id                             text,
    qco_number                         text,
    scheme_id                          text,
    scheme_name                        text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS product_document_mapping CASCADE;
CREATE TABLE product_document_mapping (
    relationship_id                    text PRIMARY KEY,
    product_id                         text,
    product_name                       text,
    document_id                        text,
    document_type                      text,
    title                              text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS test_lab_mapping CASCADE;
CREATE TABLE test_lab_mapping (
    relationship_id                    text PRIMARY KEY,
    test_id                            text,
    test_name                          text,
    lab_id                             text,
    lab_name                           text,
    capability                         text,
    testing_charge                     text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS notification_entity_mapping CASCADE;
CREATE TABLE notification_entity_mapping (
    relationship_id                    text PRIMARY KEY,
    notification_id                    text,
    notification_number                text,
    target_entity                      text,
    target_entity_id                   text,
    target_entity_label                text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_amendments CASCADE;
CREATE TABLE is_amendments (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    amendment_reference                text,
    amendment_date                     text,
    amended_from_version               text,
    amended_to_version                 text,
    amendment_status                   text,
    superseded_standard                text,
    superseding_standard               text,
    document_id                        text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_product_manual_mapping CASCADE;
CREATE TABLE is_product_manual_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    manual_id                          text,
    manual_title                       text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_fmcs_mapping CASCADE;
CREATE TABLE is_fmcs_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    fmcs_id                            text,
    cml_licence_no                     text,
    manufacturer_name                  text,
    country                            text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS entity_document_mapping CASCADE;
CREATE TABLE entity_document_mapping (
    relationship_id                    text PRIMARY KEY,
    entity_type                        text,
    entity_id                          text,
    entity_label                       text,
    document_id                        text,
    document_type                      text,
    title                              text,
    source_url                         text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS scheme_product_mapping CASCADE;
CREATE TABLE scheme_product_mapping (
    relationship_id                    text PRIMARY KEY,
    scheme_id                          text,
    scheme_name                        text,
    product_id                         text,
    product_name                       text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS hallmarking_centre_scope CASCADE;
CREATE TABLE hallmarking_centre_scope (
    relationship_id                    text PRIMARY KEY,
    centre_id                          text,
    centre_name                        text,
    scope_item                         text,
    recognition_status                 text,
    city                               text,
    state                              text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS is_entity_mapping CASCADE;
CREATE TABLE is_entity_mapping (
    relationship_id                    text PRIMARY KEY,
    is_id                              text,
    canonical_is_number                text,
    entity_type                        text,
    entity_id                          text,
    entity_label                       text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS qco_product_mapping CASCADE;
CREATE TABLE qco_product_mapping (
    relationship_id                    text PRIMARY KEY,
    qco_id                             text,
    qco_number                         text,
    product_id                         text,
    product_name                       text,
    relationship_type                  text,
    relation_context                   text,
    evidence_column                    text,
    evidence_value                     text,
    unmatched_reference                text,
    source_file_ids                    text,
    source_files                       text,
    source_sheets                      text,
    source_rows                        text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS product_manual_infrastructure CASCADE;
CREATE TABLE product_manual_infrastructure (
    pm_section_id                      text PRIMARY KEY,
    pm_id                              text,
    manual_title                       text,
    manual_version                     text,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    product_name                       text,
    section_category                   text,
    source_column                      text,
    requirement_text                   text,
    text_length                        integer,
    clause                             text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    source_url                         text,
    review_flag                        text
);

DROP TABLE IF EXISTS product_manual_marking CASCADE;
CREATE TABLE product_manual_marking (
    pm_section_id                      text PRIMARY KEY,
    pm_id                              text,
    manual_title                       text,
    manual_version                     text,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    product_name                       text,
    section_category                   text,
    source_column                      text,
    requirement_text                   text,
    text_length                        integer,
    clause                             text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    source_url                         text,
    review_flag                        text
);

DROP TABLE IF EXISTS product_manual_requirements CASCADE;
CREATE TABLE product_manual_requirements (
    pm_section_id                      text PRIMARY KEY,
    pm_id                              text,
    manual_title                       text,
    manual_version                     text,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    product_name                       text,
    section_category                   text,
    source_column                      text,
    requirement_text                   text,
    text_length                        integer,
    clause                             text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    source_url                         text,
    review_flag                        text
);

DROP TABLE IF EXISTS product_manual_sampling CASCADE;
CREATE TABLE product_manual_sampling (
    pm_section_id                      text PRIMARY KEY,
    pm_id                              text,
    manual_title                       text,
    manual_version                     text,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    product_name                       text,
    section_category                   text,
    source_column                      text,
    requirement_text                   text,
    text_length                        integer,
    clause                             text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    source_url                         text,
    review_flag                        text
);

DROP TABLE IF EXISTS product_manual_testing CASCADE;
CREATE TABLE product_manual_testing (
    pm_section_id                      text PRIMARY KEY,
    pm_id                              text,
    manual_title                       text,
    manual_version                     text,
    is_id                              text,
    canonical_is_number                text,
    product_id                         text,
    product_name                       text,
    section_category                   text,
    source_column                      text,
    requirement_text                   text,
    text_length                        integer,
    clause                             text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    source_url                         text,
    review_flag                        text
);

DROP TABLE IF EXISTS entity_attributes CASCADE;
CREATE TABLE entity_attributes (
    attribute_id                       text PRIMARY KEY,
    entity_type                        text,
    entity_id                          text,
    entity_label                       text,
    attribute_name                     text,
    attribute_value                    text,
    value_length                       integer,
    semantic_type                      text,
    attribute_context                  text,
    null_class                         text,
    original_value                     text,
    missing_reason                     text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    source_column                      text,
    transformation_rule                text,
    merge_action                       text,
    rule_source                        text,
    source_url                         text,
    review_flag                        text
);

DROP TABLE IF EXISTS record_provenance CASCADE;
CREATE TABLE record_provenance (
    provenance_id                      text PRIMARY KEY,
    provenance_origin                  text,
    entity_type                        text,
    entity_id                          text,
    entity_label                       text,
    canonical_column                   text,
    canonical_value                    text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    source_column                      text,
    source_value                       text,
    null_class                         text,
    missing_reason                     text,
    transformation_rule                text,
    merge_action                       text,
    rule_source                        text,
    record_disposition                 text,
    source_url                         text,
    source_title                       text,
    source_type                        text,
    document_id                        text,
    document_title                     text,
    page                               integer,
    section                            text,
    clause                             text,
    version                            text,
    effective_date                     text,
    document_hash                      text,
    retrieved_at                       text,
    evidence_text                      text,
    verification_status                text,
    confidence                         numeric
);

DROP TABLE IF EXISTS source_file_provenance CASCADE;
CREATE TABLE source_file_provenance (
    source_file_id                     text PRIMARY KEY,
    original_filename                  text,
    extension                          text,
    exact_path                         text,
    source_location                    text,
    sha256                             text,
    file_size_bytes                    integer,
    encoding                           text,
    sheet_name                         text,
    sheet_count                        integer,
    total_data_rows                    integer,
    total_columns                      integer,
    canonical_target                   text,
    canonical_dataset                  text,
    candidate_topic                    text,
    rows_read                          integer,
    cells_projected                    integer,
    records_canonical                  integer,
    records_merged                     integer,
    records_conflict_preserved         integer,
    records_requires_review            integer,
    records_not_applicable             integer,
    records_accounted                  integer,
    retention_decision                 text,
    archive_path                       text,
    structural_issue                   text,
    analysis_status                    text,
    modified_time_utc                  text,
    notes                              text
);

DROP TABLE IF EXISTS document_provenance CASCADE;
CREATE TABLE document_provenance (
    document_provenance_id             text PRIMARY KEY,
    document_id                        text,
    document_type                      text,
    title                              text,
    is_id                              text,
    canonical_is_number                text,
    source_url                         text,
    download_url                       text,
    local_path                         text,
    sha256                             text,
    page_count                         integer,
    http_status                        text,
    content_type                       text,
    bytes                              integer,
    last_modified                      text,
    access_type                        text,
    parser_status                      text,
    dedup_status                       text,
    retrieved_at                       text,
    chunk_count                        integer,
    evidence_row_count                 integer,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    notes                              text
);

DROP TABLE IF EXISTS conflict_status CASCADE;
CREATE TABLE conflict_status (
    conflict_id                        text PRIMARY KEY,
    entity_type                        text,
    entity_id                          text,
    entity_label                       text,
    field                              text,
    source_a                           text,
    source_a_file_id                   text,
    value_a                            text,
    source_row_a                       integer,
    date_a                             text,
    source_b                           text,
    source_b_file_id                   text,
    value_b                            text,
    source_row_b                       integer,
    date_b                             text,
    resolution_status                  text,
    resolution_rule                    text,
    resolution_reason                  text,
    canonical_value                    text,
    confidence                         numeric,
    review_flag                        text
);

DROP TABLE IF EXISTS requires_review CASCADE;
CREATE TABLE requires_review (
    review_id                          text PRIMARY KEY,
    entity_type                        text,
    entity_id                          text,
    entity_label                       text,
    field                              text,
    field_value                        text,
    review_class                       text,
    review_reason                      text,
    required_action                    text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    attempted_source_url               text,
    phase2_verdict                     text,
    resolution_status                  text
);

DROP TABLE IF EXISTS data_loss_audit CASCADE;
CREATE TABLE data_loss_audit (
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    route_target                       text,
    entity_type                        text,
    entity_id                          text,
    entity_label                       text,
    record_disposition                 text,
    disposition_reason                 text,
    fields_projected                   integer,
    fields_populated                   integer,
    attributes_written                 integer,
    relationships_written              integer,
    provenance_rows                    integer
);

DROP TABLE IF EXISTS orphan_records CASCADE;
CREATE TABLE orphan_records (
    relationship_table                 text,
    relationship_type                  text,
    unmatched_reference                text,
    evidence_column                    text,
    evidence_value                     text,
    resolved_sides                     text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    reason                             text
);

DROP TABLE IF EXISTS extraction_log CASCADE;
CREATE TABLE extraction_log (
    url                                text,
    error_type                         text,
    event_timestamp                    text,
    retry_count                        text,
    outcome                            text,
    notes                              text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    record_disposition                 text
);

DROP TABLE IF EXISTS fmcs_country_coverage CASCADE;
CREATE TABLE fmcs_country_coverage (
    country                            text,
    manufacturer_count                 text,
    licence_count                      text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    record_disposition                 text
);

DROP TABLE IF EXISTS fmcs_is_coverage CASCADE;
CREATE TABLE fmcs_is_coverage (
    is_id                              text,
    canonical_is_number                text,
    manufacturer_count                 text,
    licence_count                      text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    record_disposition                 text
);

DROP TABLE IF EXISTS lab_scope CASCADE;
CREATE TABLE lab_scope (
    lab_id                             text,
    test_id                            text,
    is_id                              text,
    source_scope_ids                   text,
    source_lab_ids                     text,
    canonical_is_number                text,
    product_name                       text,
    test_name                          text,
    test_method_standard               text,
    clause_reference                   text,
    capability                         text,
    scope_status                       text,
    scope_validity                     text,
    testing_charge                     text,
    source_url                         text,
    source_file_id                     text,
    source_file                        text,
    source_sheet                       text,
    source_row                         integer,
    record_disposition                 text
);

-- Relationship rows whose defining endpoint could not be resolved to a
-- canonical entity. Review data, deliberately outside the production
-- relationship tables so those carry no unresolved foreign keys.
DROP TABLE IF EXISTS unresolved_relationship_references CASCADE;
CREATE TABLE unresolved_relationship_references (
    quarantine_id TEXT,
    origin_table TEXT,
    relationship_id TEXT,
    relationship_type TEXT,
    resolved_side_entity_type TEXT,
    resolved_side_entity_id TEXT,
    resolved_side_label TEXT,
    unresolved_side_role TEXT,
    unresolved_side_reference TEXT,
    evidence_column TEXT,
    evidence_value TEXT,
    source_file_id TEXT,
    source_file TEXT,
    source_sheet TEXT,
    source_row TEXT,
    quarantine_reason TEXT,
    retained_in TEXT,
    confidence TEXT,
    PRIMARY KEY (quarantine_id)
);


-- ===================== SECTION 2: PHASE-4 ALIAS VIEWS ====================
-- Names used by the Phase-4 smoke tests. A view is not a copy: one source of
-- truth per table is preserved.
CREATE OR REPLACE VIEW bis.standards AS SELECT * FROM bis.is_master;
CREATE OR REPLACE VIEW bis.products AS SELECT * FROM bis.product_master;
CREATE OR REPLACE VIEW bis.qcos AS SELECT * FROM bis.qco_master;
CREATE OR REPLACE VIEW bis.schemes AS SELECT * FROM bis.scheme_master;
CREATE OR REPLACE VIEW bis.documents AS SELECT * FROM bis.document_master;
CREATE OR REPLACE VIEW bis.product_manuals AS SELECT * FROM bis.product_manual_master;
CREATE OR REPLACE VIEW bis.tests AS SELECT * FROM bis.test_master;
CREATE OR REPLACE VIEW bis.labs AS SELECT * FROM bis.lab_master;
CREATE OR REPLACE VIEW bis.faq AS SELECT * FROM bis.faq_master;
CREATE OR REPLACE VIEW bis.notifications AS SELECT * FROM bis.notification_master;
CREATE OR REPLACE VIEW bis.legal AS SELECT * FROM bis.legal_master;
CREATE OR REPLACE VIEW bis.hallmarking AS SELECT * FROM bis.hallmarking_master;
CREATE OR REPLACE VIEW bis.fmcs AS SELECT * FROM bis.fmcs_master;

-- Relationship tables already carry the spec's names, so they need no views.
